# all available options: https://goreleaser.com/customization/
project_name: summon

before:
  hooks:
  - go mod download

builds:
- id: summon
  binary: summon
  env:
  - CGO_ENABLED=0
  flags:
  - -tags=netgo
  goos:
  - darwin  # MacOS
  - solaris
  - windows
  goarch:
  - amd64
  main: ./cmd/main.go

# Apple silicon support
- id: summon-arm
  binary: summon
  env:
  - CGO_ENABLED=0
  flags:
  - -tags=netgo
  goos:
  - darwin  # MacOS
  goarch:
  - arm64
  main: ./cmd/main.go

# Make a static build for Linux
- id: summon-linux
  binary: summon
  env:
  - CGO_ENABLED=1
  flags:
  - -tags=netgo
  goos:
  - linux
  goarch:
  - amd64
  ldflags: -s -w -linkmode external -extldflags "-static"
  main: ./cmd/main.go


archives:
  - id: summon-release-archive
    name_template: "{{.ProjectName}}-{{.Os}}-{{.Arch}}"
    format_overrides:
    - goos: windows
      format: zip
    files:
      - none*  # only package the binary - not defaults: readme, license, changelog

checksum:
  name_template: 'SHA256SUMS.txt'

brews:
  - description: CLI that provides on-demand secrets access for common DevOps tools.
    homepage: https://github.com/cyberark/summon
    url_template: https://github.com/cyberark/summon/releases/download/v{{.Version}}/summon-{{ tolower .Os }}-{{ tolower .Arch }}.tar.gz
    install: |
      bin.install "summon"
    test: |
      system "#{bin}/summon", "-v"

    tap:
      owner: cyberark
      name: homebrew-tools
    skip_upload: true

nfpms:
  - file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Arch }}"
    vendor: CyberArk
    homepage: https://github.com/cyberark/summon
    maintainer: Conjur Maintainers <conj_maintainers@cyberark.com>

    description: CLI that provides on-demand secrets access for common DevOps tools.
    recommends:
      - summon-conjur
    license: MIT
    formats:
    - deb
    - rpm
    - apk
    bindir: /usr/local/bin

dist: ./dist/goreleaser

release:
  disable: false
  draft: true
  extra_files:
    - glob: LICENSE
    - glob: CHANGELOG.md
